EnvironmentCrime/Controllers/CitizenController.cs
using EnvironmentCrime.Models;
using Microsoft.AspNetCore.Mvc;
using EnvironmentCrime.Infrastructure;

namespace EnvironmentCrime.Controllers
{
    public class CitizenController : Controller
    {
        private readonly IRepository repository;

        public CitizenController(IRepository repo)
        {
            repository = repo;
        }
    
        public ViewResult Contact()
        {
            return View();
        }

        public ViewResult Faq()
        {
            return View();
        }

        public ViewResult Services()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Validate(Errand errand)
        {
            HttpContext.Session.Set<Errand>("NewErrand", errand);
            return View(errand);
        }


        public ViewResult Thanks()
        {
            var dbEntry = HttpContext.Session.Get<Errand>("NewErrand");
            repository.SaveErrand(dbEntry);
            ViewBag.RefNumber = dbEntry.RefNumber;
            HttpContext.Session.Remove("NewErrand");
            return View();
        }
    }
}

EnvironmentCrime/Controllers/HomeController.cs
using EnvironmentCrime.Models;
using Microsoft.AspNetCore.Mvc;
using EnvironmentCrime.Infrastructure;

namespace EnvironmentCrime.Controllers
{
    public class HomeController : Controller
    {

        private readonly IRepository repository;

        public HomeController(IRepository repository)
        {
            this.repository = repository;
        }

        public ViewResult Index()
        {
            var tempErrand = HttpContext.Session.Get<Errand>("NewErrand");

            if(tempErrand == null)
            {
                return View();
            }
            else
            {
                return View(tempErrand);
            }
        }
        
        public ViewResult Login()
        {
            return View();
        }        
    }
}

EnvironmentCrime/Views/Home/Index.cshtml
@model Errand

@{
	Layout = "_CitizenLayout";
}


<h2>Välkommen att fylla i din anmälan av miljöbrott</h2>
<p class="info">I Småstad är inga brott för små för att anmälas</p>

<p>Fyll i formuläret nedan, alla rutor markerade med stjärna (*) måste fyllas i.</p>

<form asp-controller="Citizen" asp-action="Validate" method="post">
	<div asp-validation-summary="All"></div>

	<p>
		<input type="hidden" name="isSubmitted" value="true" />
	</p>
	<p>
		<label class="label" asp-for="Place"></label><br />		
		<input asp-for="Place"/> *
	</p>
	<p>
		<label asp-for="TypeOfCrime"></label><br />
		<input asp-for="TypeOfCrime"/> *
	</p>
	<p>
		<label asp-for="DateOfObservation"></label><br />
		<input asp-for="DateOfObservation"/> *
	</p>
	<p>
		<label asp-for="InformerName"></label><br />
		<input asp-for="InformerName"/> *
	</p>
	<p>
		<label asp-for="InformerPhone"></label><br />
		<input asp-for="InformerPhone"/> *
	</p>
	<p>
		<span class="label">
			<label asp-for="Observation">Beskriv din observation<br /> (ex. namn på misstänkt person): </label><br />
		</span>
		<textarea name="observation" asp-for="Observation" rows="5" cols="16"></textarea>
	</p>
	<p>
		<input class="button" type="submit" value="Skicka in" />
	</p>
</form>

EnvironmentCrime/Views/Home/Login.cshtml
@model LoginModel

@{
    Layout = "_CitizenLayout";
}

<h2>Inloggning för Småstads personal</h2>
<p class="info">En säker tjänst från Småstads IT-avdelning</p>

<form method="post" asp-controller="Account" asp-action="Login">
    <p>
        <input type="hidden" name="isSubmitted" value="true" />
    </p>
        
    <p>
        <span class="label" asp-validation-for="UserName">Användarnamn:</span><br />
        <input type="text" asp-for="UserName" />
        <span asp-validation-for="UserName" />
    </p>

    <p>
        <span class="label" asp-validation-for="Password">Lösenord:</span><br />
        <input type="password" asp-for="Password" />
        <span asp-validation-for="Password" />
    </p>

    <p>
        <input type="hidden" asp-for="ReturnUrl" />
    </p>

    <p>
        <input class="button" type="submit" value="Logga in" />
        <br />
    </p>

    <div asp-validation-summary="All"></div>

</form>