EnvironmentCrime/Components/ErrandViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using EnvironmentCrime.Models;

namespace EnvironmentCrime.Components
{
    public class ErrandViewComponent : ViewComponent
    {

        private readonly IRepository repository;

        public ErrandViewComponent(IRepository repository)
        {
            this.repository = repository;
        }


        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            var errandInfo = await repository.GetErrandInfo(id);
            return View("Errand", errandInfo);
        }

    }
}

EnvironmentCrime/Components/LoggedInViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using EnvironmentCrime.Models;

namespace EnvironmentCrime.Components
{
    public class LoggedInViewComponent : ViewComponent
    {
        private readonly IRepository repository;

        public LoggedInViewComponent(IRepository repository)
        {
            this.repository = repository;
        }

        public IViewComponentResult Invoke()
        {

            ViewBag.User = "";

            if (User.IsInRole("Coordinator"))
            {
                ViewBag.User = "samordnare";
            }
            else if(User.IsInRole("Manager"))
            {
                ViewBag.User = "avdelningschef";
            }
            else if (User.IsInRole("Investigator"))
            {
                ViewBag.User = "handläggare";
            }

            return View("LoggedIn");
        }


    }
}

EnvironmentCrime/Controllers/CoordinatorController.cs
using Microsoft.AspNetCore.Mvc;
using EnvironmentCrime.Models;
using EnvironmentCrime.Infrastructure;
using Microsoft.AspNetCore.Authorization;

namespace EnvironmentCrime.Controllers
{
    [Authorize(Roles = "Coordinator")]
    public class CoordinatorController : Controller
    {
        private readonly IRepository repository;
        private IHttpContextAccessor contextAcc;

        public CoordinatorController(IRepository repo, IHttpContextAccessor contextAcc)
        {
            repository = repo;
            this.contextAcc = contextAcc;
        }

        public ViewResult StartCoordinator()
        {
            var tempErrand = HttpContext.Session.Get<Errand>("NewErrand");

            @ViewBag.UserName = contextAcc.HttpContext.User.Identity.Name;
            ViewBag.ErrandList = repository.ShowErrandListCoordinator();

            return View();
        }

        public ViewResult CrimeCoordinator(int id)
        {
            TempData["ID"] = id;
            ViewBag.ID = id;
            ViewBag.DepartmentList = repository.Departments;
            return View();
        }

        public ViewResult ReportCrime()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Validate(Errand errand)
        {
            HttpContext.Session.Set<Errand>("NewErrand", errand);
            return View(errand);
        }

        public ViewResult Thanks()
        {
            var dbEntry = HttpContext.Session.Get<Errand>("NewErrand");
            repository.SaveErrand(dbEntry);
            ViewBag.RefNumber = dbEntry.RefNumber;
            HttpContext.Session.Remove("NewErrand");
            return View();
        }


        //Helper method to save choice from dropdown menu to database:
        public IActionResult AssignDepartmentToErrand(Department department)
        {
            int ErrandId = int.Parse(TempData["ID"].ToString());

            repository.UpdateErrandWithDepartmentId(ErrandId, department.DepartmentId);

            return RedirectToAction("StartCoordinator");
        }

    }
}

EnvironmentCrime/Views/Coordinator/CrimeCoordinator.cshtml
@model Department

@{
    Layout = "_CoordinatorLayout";
}

<h2>Detaljer för ärendet</h2>
@await Component.InvokeAsync("LoggedIn")

<!--Nedan kommer ViewComponent att klistras in-->
@await Component.InvokeAsync("Errand", ViewBag.ID)


<!--Nedan kopplar koordinatorn en avdelning till ett ärende-->
<section id="bottomColumn">
    <h3>Redigera ärende</h3>

    <form asp-controller="Coordinator" asp-action="AssignDepartmentToErrand" asp-route-id="ViewBag.ID" method="post">
        <p>
            Ange enhet:
            <select asp-for="DepartmentId" asp-items="@(new SelectList(ViewBag.DepartmentList, "DepartmentId", "DepartmentName"))">
                <option selected="selected">Välj</option>
            </select>
        </p>

        <p>
            <input class="button" type="submit" value="Spara ändringarna" />
        </p>

    </form>
</section>

EnvironmentCrime/Views/Coordinator/ReportCrime.cshtml
@model Errand

@{
    Layout="_CoordinatorLayout";
}

<h2>Rapportera brott</h2>
@await Component.InvokeAsync("LoggedIn")

<p>Fyll i formuläret nedan, alla rutor markerade med stjärna (*) måste fyllas i</p>
    
<form asp-controller="Coordinator" asp-action="Validate" method="post">
    <div asp-validation-summary="All"></div>

    <p>
        <input type="hidden" name="isSubmitted" value="true" />
    </p>
    <p>
        <label class="label" asp-for="Place"></label><br />
        <input asp-for="Place" /> *
    </p>
    <p>
        <label asp-for="TypeOfCrime"></label><br />
        <input asp-for="TypeOfCrime" /> *
    </p>
    <p>
        <label asp-for="DateOfObservation"></label><br />
        <input asp-for="DateOfObservation" /> *
    </p>
    <p>
        <label asp-for="InformerName"></label><br />
        <input asp-for="InformerName" /> *
    </p>
    <p>
        <label asp-for="InformerPhone"></label><br />
        <input asp-for="InformerPhone" /> *
    </p>
    <p>
        <span class="label">
            <label asp-for="Observation">Beskriv din observation<br /> (ex. namn på misstänkt person): </label><br />
        </span>
        <textarea name="observation" asp-for="Observation" rows="5" cols="16"></textarea>
    </p>
    <p>
        <input class="button" type="submit" value="Skicka in" />
    </p>
</form>

EnvironmentCrime/Views/Coordinator/StartCoordinator.cshtml
@model MyErrand

@{
    Layout = "_CoordinatorLayout";
    List<String> StatusCategories = new List<String>();
    List<String> DepartmentNames = new List<String>();
}

<h2>Ärenden</h2>
@await Component.InvokeAsync("LoggedIn")

<table id="managerForm">
    <tr>
        <td class="label">Välj status:</td>
        <td class="label">Välj avdelning:</td>
        <td>&nbsp;</td>
        <td class="label">Ärendenummer:</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td>
            <select name="status">
                <option selected="selected">Välj alla</option>
                
                @foreach(MyErrand errand in ViewBag.ErrandList)
                {
                    if(!StatusCategories.Contains(errand.StatusName))
                    {
                        <option>@errand.StatusName</option>
                        StatusCategories.Add(errand.StatusName);
                    }
                }

            </select>
        </td>


        <td>
            <select name="department">
                <option selected="selected">Välj alla</option>

                @foreach(MyErrand errand in ViewBag.ErrandList)
                {
                    if (!DepartmentNames.Contains(errand.DepartmentName))
                    {
                        <option>@errand.DepartmentName</option>
                        DepartmentNames.Add(errand.DepartmentName);
                    }
                }

            </select>
        </td>
        <td><input class="button" type="submit" value="Hämta lista" /></td>
        <td><input name="casenumber" /></td>
        <td><input class="button" type="submit" value="Sök" /></td>
    </tr>
</table>

<!--Nedan ser man en lista på ärenden-->
<table>
    <tr>
        <th>Ärende anmält</th>
        <th>Ärendenummer</th>
        <th>Miljöbrott</th>
        <th>Status</th>
        <th>Avdelning</th>
        <th>Handläggare</th>
    </tr>

    @foreach(MyErrand errand in ViewBag.ErrandList)
    {
        <tr>
            <td>@errand.DateOfObservation.ToShortDateString()</td>
            <td><a asp-controller="Coordinator" asp-action="CrimeCoordinator" asp-route-id="@errand.ErrandId">@errand.RefNumber </a></td>
            <td>@errand.TypeOfCrime</td>
            <td>@errand.StatusName</td> 
            <td>@errand.DepartmentName</td>
            <td>@errand.EmployeeName</td>
        </tr>
    }
</table>

EnvironmentCrime/Views/Coordinator/Thanks.cshtml
@model Errand

@{
    Layout = "_CoordinatorLayout";
}

<h2>Tack för din anmälan</h2>
@await Component.InvokeAsync("LoggedIn")

<p>
    Anmälan har nu skickats in till kommunen och kommer att utredas. <br />
    Vill du komplettera din anmälan kontakta oss via mail eller telefon. <br />
    Ange då nummer: @Model.RefNumber
</p>

<p><a class="button" asp-controller="Coordinator" asp-action="StartCoordinator">Avsluta rapporteringen</a></p>

EnvironmentCrime/Views/Coordinator/Validate.cshtml
@model Errand

@{
    Layout = "_CoordinatorLayout";
}

<h2>Din anmälan av miljöbrott</h2>
@await Component.InvokeAsync("LoggedIn")

<p class="label">
    Vänligen läs igenom din anmälan och se att allt är okej.<br />
    Om något är fel, gå tillbaka och ändra. Annars välj Bekräfta.
</p>


<p><span class="label">Var har brottet skett någonstans?</span><br />@Model.Place</p>
<p><span class="label">Vilken typ av brott?</span><br />@Model.TypeOfCrime</p>
<p><span class="label">När skedde brottet?</span><br />@Model.DateOfObservation.ToShortDateString()</p>
<p><span class="label">Ditt namn (för- och efternamn):</span><br />@Model.InformerName</p>
<p><span class="label">Din telefon:</span><br />@Model.InformerPhone</p>
<p><span class="label">Mer information:</span><br />@Model.Observation</p>
<p>
    <a class="button" asp-controller="Home" asp-action="Index" id="link">Tillbaka</a>
    <a class="button" asp-controller="Coordinator" asp-action="Thanks">Bekräfta</a>
</p>